name: py37-snakelips-3d
channels:
  - defaults
  - conda-forge
dependencies:
  - python >=3.7,<3.8
  - h5py ==2.10.0
  - lxml ==4.5.0
  - matplotlib ==3.4.3
  - numpy ==1.20.3
  - pandas ==1.2.4
  - pip
  - pyvista ==0.33.3
  - pyyaml ==5.3.1
  - scipy ==1.4.1
  - tqdm ==4.63.0
  - vtk ==9.1.0
  - pip:
    - git+https://github.com/mesnardo/petibmpy@v0.2
