#!/usr/bin/env bash

# Run from this directory.
cd ${0%/*} || exit 1

# Source tool run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Meshrun

# Run potential flow solver.
runParallel potentialFoam

# Run OpenFOAM solver.
runParallel $(getApplication)

# Reconstruct the latest solution.
runApplication reconstructPar -latestTime

#------------------------------------------------------------------------------
