#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions.
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Remove initial and boundary conditions.
rm -rf 0

# Remove surface and features.
rm -f constant/triSurface/*.eMesh
rm -rf constant/extendedFeatureEdgeMesh

cleanCase

#------------------------------------------------------------------------------
